language: rust
rust: stable
sudo: required
dist: trusty

git:
  depth: 1

# Using 'cache: cargo' to cache target/ and all of $HOME/.cargo/
# doesn't work well: the cache is large and it takes several minutes
# to move it to and from S3. So instead we only cache the mdbook
# binary.
cache:
  directories:
    - $HOME/.cargo/bin/

matrix:
  include:
    - env: TARGET=x86_64-apple-darwin
           ALT=i686-apple-darwin
      os: osx
      osx_image: xcode9.1
    - env: TARGET=x86_64-apple-darwin
           ALT=i686-apple-darwin
      os: osx
      osx_image: xcode9.2
    - env: TARGET=x86_64-apple-darwin
           ALT=i686-apple-darwin
      os: osx
      osx_image: xcode9.3
    - env: TARGET=x86_64-apple-darwin
           ALT=i686-apple-darwin
      os: osx
      osx_image: xcode9.4
    - env: TARGET=x86_64-apple-darwin
           ALT=i686-apple-darwin
      os: osx
      osx_image: xcode10
    - env: TARGET=x86_64-apple-darwin
           ALT=i686-apple-darwin
      os: osx
      osx_image: xcode10.1

  exclude:
    - rust: stable

before_script:
  - rustup target add $ALT
script:
  - cargo test

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - gcc-multilib
