trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-test-all.yml
    strategy:
      matrix:
        stable:
          TOOLCHAIN: stable
        beta:
          TOOLCHAIN: beta
        nightly:
          TOOLCHAIN: nightly
    variables:
      ALT: i686-unknown-linux-gnu

  - job: macOS
    pool:
      vmImage: macos-10.13
    steps:
      - template: ci/azure-test-all.yml
    strategy:
      matrix:
        stable:
          TOOLCHAIN: stable
    variables:
      ALT: i686-apple-darwin

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ci/azure-test-all.yml
    strategy:
      matrix:
        stable:
          TOOLCHAIN: stable
    variables:
      ALT: i686-pc-windows-msvc

  - job: docs
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
      - script: curl -Lf https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.7/mdbook-v0.1.7-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=$HOME/.cargo/bin
        displayName: "Install mdbook"
      - script: cargo doc --no-deps
        displayName: "Build API docs"
      - script: cd src/doc && mdbook build --dest-dir ../../target/doc
        displayName: "Build mdbook docs"
